services:
  postgres:
    image: postgres:16
    container_name: eticket-postgres
    environment:
      POSTGRES_DB: eticketdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}", "-d", "eticketdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: shamim7999/e-ticket:latest
    container_name: eticket-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

volumes:
  pgdata:
